# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9295e76c2b656fc67c13eb65bcc3e84d31854bd58d739b1c78d3f6d7dda38dd6ffd140d05f5b1298c4d2133f0b32e28f93375e93caa7bbf06bba8be4c09fd223

test:
  secret_key_base: 81255f0e6a33e12b76747e6392a1e200b756ec188428a7a0f2fb6d9ab5e303acf5ad78ed17a7c4725352ddfabd88cc82cb9c3a58aedfdfc9a3e5cc16c23b6e39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
